### PR TITLE
PWA

### PR DESCRIPTION
**Pull request by sillyangel**
make the website installable, in Phones, Tablets, and even Chromebooks!

### CODE REVIEW

**Comment by sillyangel** [comment]
i wanna cry

**Comment by OutRed** [comment]
So what is this?

**Comment by sillyangel** [comment]
pwa to install i few photos on how it works

**Comment by sillyangel** [comment]
- Pc

**Comment by sillyangel** [comment]
- chromebook
image

**Comment by OutRed** [comment]
That's actually 🔥. Are you in the discord? I'll prob merge this

**Pull request merged**
